const calendarActions = {
  GENERATING_CALENDAR: 'calendar/GENERATING_CALENDAR',
  RESET_CALENDAR: 'calendar/RESET_CALENDAR',
  SET_CALENDAR: 'calendar/SET_CALENDAR',
  COUNTRIES_LOADING: 'calendar/COUNTRIES_LOADING',
  COUNTRIES_LOADED: 'calendar/COUNTRIES_LOADED',
  HOLIDAYS_LOADING: 'calendar/HOLIDAYS_LOADING',
  HOLIDAYS_LOADED: 'calendar/HOLIDAYS_LOADED',
  FIELD_CHANGE: 'calendar/FIELD_CHANGE',
};

export default calendarActions;
